name: CI/CD by Sync Zipped HTML to S3

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      # Step 2: Set up AWS CLI
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Change to your preferred region

      # Step 3: Install zip utility
      - name: Install zip
        run: sudo apt-get install -y zip

      # Step 4: Zip the HTML file
      - name: Zip the HTML file
        run: |
          if ls index.html 1> /dev/null 2>&1; then
            zip -r index.zip index.html
          else
            echo "No HTML files found to zip."
            exit 1
          fi

      # Step 5: Sync the zipped file to the S3 bucket
      - name: Deploy to S3
        run: |
          aws s3 cp html-files.zip s3://uco-cicc-media/proj3/